{% set version = "1.2.1" %}

package:
  name: basemap
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}rel.tar.gz
  sha256: 3fb30424f18cd4ffd505e30fd9c810ae81b999bb92f950c76553e1abc081faa7
  patches:
    - data.patch

build:
  number: 3
  skip: True  # [win and py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - geos
    - matplotlib-base >=1.0.0,!=3.0.1
    - pyproj >=1.9.3
    - proj4 >=4.9.3
    - pyshp >=1.2.0
    - six
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - geos
    - matplotlib-base >=1.0.0,!=3.0.1
    - pyproj >=1.9.3
    - pyshp >=1.2.0
    - proj4 >=4.9.3
    - six

test:
  imports:
    - mpl_toolkits.basemap

about:
  home: http://matplotlib.org/basemap
  license: MIT
  license_file: README.md
  summary: 'Plot on map projections using matplotlib'

extra:
  recipe-maintainers:
    - ocefpaf
