{% set version = "1.2.1" %}

package:
  name: basemap
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}rel.tar.gz
  sha256: 3fb30424f18cd4ffd505e30fd9c810ae81b999bb92f950c76553e1abc081faa7
  patches:
    - basemap-1.0.8dev-datadir.patch
    - use_proj_data.patch

build:
  number: 0
  skip: True  # [win and py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - geos
    - matplotlib-base >=1.0.0
    - pyproj >=1.9.3,<2
    - pyshp >=1.2.0
    - six
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - geos
    - matplotlib-base >=1.0.0
    - pyproj >=1.9.3,<2
    - pyshp >=1.2.0
    - six

test:
  imports:
    - mpl_toolkits.basemap

about:
  home: http://matplotlib.org/basemap
  license: MIT
  license_file: README.md
  summary: 'Plot on map projections using matplotlib'
  description: |
    Basemap toolkit is a library for plotting 2D data on maps in Python.
    It is similar in functionality to the matlab mapping toolbox, the IDL mapping facilities, GrADS, or the Generic Mapping Tools.
  doc_url: http://matplotlib.org/basemap/
  doc_source_url: https://github.com/matplotlib/basemap/blob/master/doc/index.rst

extra:
  recipe-maintainers:
    - ocefpaf
