{% set version = "1.3.9" %}
{% set build_number = 0 %}

{% set data_version = "1.3.2" %}
{% set data_build_number = 0 %}

package:
  name: basemap-split
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}.tar.gz
  sha256: 44ae3764595778077d4bc40b0756c90f483b816927e82206e9f376e31a2dc533
  patches:
    - fix_install_hires_instructions.patch
    - fix_numpy_requirements.patch

build:
  skip: true  # [python_impl == 'pypy']
  # Missing dependencies in s390x.
  skip: true  # [s390x]
  # Missing dependencies in win32 and not expecting they will be updated.
  skip: true  # [win32]

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [not win]

outputs:

  - name: basemap
    version: {{ version }}
    # These scripts will delete `pyproject.toml`. Remove ASAP.
    script: build-basemap.sh  # [not win]
    script: bld-basemap.bat   # [win]
    build:
      number: {{ build_number }}
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - cython >=0.29,<3.0                  # [build_platform != target_platform]
        - numpy >=1.21                        # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - pip
        - setuptools
        - wheel
        - cython >=0.29,<3.0
        - numpy >=1.21
        - geos
        - pyproj
      run:
        - python
        - {{ pin_compatible('basemap-data', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('numpy') }}
        - {{ pin_compatible('geos') }}
        - matplotlib-base >=1.5,<3.8
        - pyproj >=1.9.3,<3.7.0
        - pyshp >=1.2.0,<2.4.0
    test:
      imports:
        - mpl_toolkits.basemap
      requires:
        - pip
        - {{ pin_compatible('basemap-data', min_pin='x.x', max_pin='x.x') }}
      commands:
        - pip check
        - python -c "from mpl_toolkits.basemap import Basemap"
    about:
      home: https://matplotlib.org/basemap
      license: MIT
      license_family: MIT
      license_file:
        - packages/basemap/LICENSE
      summary: Plot data on map projections with matplotlib
      description: |
        Basemap toolkit is a library for plotting 2D data on maps in Python.
        It is similar in functionality to the matlab mapping toolbox,
        the IDL mapping facilities, GrADS, or the Generic Mapping Tools.
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/
      doc_source_url: https://github.com/matplotlib/basemap/blob/v{{ version }}/packages/basemap/doc/index.rst

{% if build_platform == target_platform %}
  - name: basemap-data
    version: {{ data_version }}
    script: build-basemap.sh  # [not win]
    script: bld-basemap.bat   # [win]
    build:
      number: {{ data_build_number }}
      noarch: python
    requirements:
      host:
        - pip
        - setuptools
        - wheel
      run:
        - python
    about:
      home: https://matplotlib.org/basemap
      license: LGPL-3.0-or-later
      license_family: LGPL
      license_file: packages/basemap_data/COPYING.LESSER
      summary: Data assets for matplotlib basemap
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/
      doc_source_url: https://github.com/matplotlib/basemap/blob/v{{ data_version }}/packages/basemap/doc/index.rst

  - name: basemap-data-hires
    version: {{ data_version }}
    script: build-basemap.sh  # [not win]
    script: bld-basemap.bat   # [win]
    build:
      number: {{ data_build_number }}
      noarch: python
    requirements:
      host:
        - pip
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage('basemap-data', min_pin='x.x', max_pin='x.x') }}
    about:
      home: https://matplotlib.org/basemap
      license: LGPL-3.0-or-later
      license_family: LGPL
      license_file: packages/basemap_data_hires/COPYING.LESSER
      summary: High-resolution data assets for matplotlib basemap
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/
      doc_source_url: https://github.com/matplotlib/basemap/blob/v{{ data_version }}/packages/basemap/doc/index.rst
{% endif %}

about:
  home: https://matplotlib.org/basemap
  license: MIT
  license_family: MIT
  summary: Split feedstock for basemap
  license_file:
    - packages/basemap/LICENSE

extra:
  recipe-maintainers:
    - molinav
    - ocefpaf
    - ReimarBauer
