{% set version = "1.0.8.dev0" %}
{% set commit = "b80bfdc34da508c247bb2124b6cc5f025c4f1b46" %}

package:
  name: basemap
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/matplotlib/basemap/archive/{{ commit }}.tar.gz
  sha256: fe697260e981135d1fe86f3560ff581ed5239239697b9b17d14890c3b897156e
  patches:
    - basemap-1.0.8dev-datadir.patch

build:
  number: 4

requirements:
  build:
    - python
    - numpy x.x
    - geos 3.4.*
  run:
    - python
    - numpy x.x
    - geos 3.4.*
    - matplotlib
    - pyproj
    - pyshp

test:
  imports:
    - mpl_toolkits.basemap
  #commands:
    #- conda inspect linkages -p $PREFIX basemap  # [not win]
    #- conda inspect objects -p $PREFIX basemap  # [osx]

about:
  home: http://matplotlib.org/basemap
  license: MIT
  summary: 'Plot on map projections using matplotlib.'

extra:
  recipe-maintainers:
    - ocefpaf
