{% set version = "1.2.0" %}

package:
  name: basemap
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}rel.tar.gz
  sha256: bd5bf305918a2eb675939873b735238f9e3dfe6b5c290e37c41e5b082ff3639a
  patches:
    - basemap-1.0.8dev-datadir.patch
    - use_proj_data.patch

build:
  number: 3
  skip: True  # [win and py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - geos
    - matplotlib-base >=1.0.0
    - pyproj >=1.9.3,<2
    - pyshp >=1.2.0
    - six
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - geos
    - matplotlib-base >=1.0.0
    - pyproj >=1.9.3,<2
    - pyshp >=1.2.0
    - six

test:
  imports:
    - mpl_toolkits.basemap

about:
  home: http://matplotlib.org/basemap
  license: MIT
  license_file: README.md
  summary: 'Plot on map projections using matplotlib'

extra:
  recipe-maintainers:
    - ocefpaf
