{% set commit = "bcad813b56e5c4cc9295760ac6683b46aecfd534" %}
{% set version = "1.3.0" %}

package:
  name: basemap
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/{{ commit }}.tar.gz
  sha256: 55b79c5ce09f153339c3a079eed2f739a0f2d6e5f933862b26fc70d026a8a4c1
  patches:
    - data.patch

build:
  number: 2
  skip: True  # [win and py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - geos
    - pyproj
    - proj
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - geos
    - matplotlib-base >=1.0.0,!=3.0.1
    - pyproj
    - pyshp >=1.2.0
    - proj
    - six

test:
  imports:
    - mpl_toolkits.basemap

about:
  home: http://matplotlib.org/basemap
  license: MIT
  license_file: README.md
  summary: 'Plot on map projections using matplotlib'

extra:
  recipe-maintainers:
    - ocefpaf
