{% set version = "1.3.6" %}
{% set build_number = 2 %}

package:
  name: basemap-split
  version: {{ version }}

source:
  url: https://github.com/matplotlib/basemap/archive/v{{ version }}.tar.gz
  sha256: 42adbd039b4afbe93ca2fa32cfab456d4fd590cb8ed1c28e4aa94dcb957b58ac
  patches:
    - fix_install_hires_instructions.patch
    - fix_numpy_requirements.patch

build:
  number: {{ build_number }}
  skip: true  # [s390x]  Missing dependencies.
  skip: true  # [win32]  Missing dependencies in win32 arch and not expecting they will be updated.
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [not win]

outputs:

  - name: basemap
    script: build-basemap.sh  # [not win]  This script will delete `pyproject.toml`. Remove ASAP.
    script: bld-basemap.bat   # [win]  This script will delete `pyproject.toml`. Remove ASAP.
    build:
      skip: true  # [python_impl == 'pypy']
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - setuptools <60.0.0                  # [build_platform != target_platform]
        - numpy >=1.21                        # [build_platform != target_platform]
        - cython                              # [build_platform != target_platform]
        - geos                                # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - pip
        - setuptools <60.0.0
        - numpy >=1.21
        - cython
        - geos
      run:
        - python
        - {{ pin_subpackage('basemap-data') }}
        - {{ pin_compatible('numpy') }}
        - {{ pin_compatible('geos') }}
        - matplotlib-base >=1.5,!=3.0.1,<3.7
        - pyproj >=1.9.3,<3.5
        - pyshp >=1.2.0,<2.4
    test:
      imports:
        - mpl_toolkits.basemap
      requires:
        - pip
        - {{ pin_subpackage('basemap-data') }}
      commands:
        - pip check
        - python -c "from mpl_toolkits.basemap import Basemap"
    about:
      home: https://matplotlib.org/basemap
      license: MIT
      license_family: MIT
      license_file:
        - packages/basemap/LICENSE
      summary: Plot on map projections using matplotlib
      description: |
        Basemap toolkit is a library for plotting 2D data on maps in Python.
        It is similar in functionality to the matlab mapping toolbox, the IDL
        mapping facilities, GrADS, or the Generic Mapping Tools.
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/
      doc_source_url: https://github.com/matplotlib/basemap/blob/v{{ version }}/packages/basemap/doc/index.rst

  - name: basemap-data
    version: 1.3.2
    script: build-basemap.sh  # [not win]
    script: bld-basemap.bat   # [win]
    build:
      noarch: python
    requirements:
      host:
        - pip
        - setuptools <60.0.0
      run:
        - python
    about:
      home: https://matplotlib.org/basemap
      license: LGPL-3.0-or-later
      license_family: LGPL
      license_file: packages/basemap_data/COPYING.LESSER
      summary: Data assets for matplotlib basemap.
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/
      doc_source_url: https://github.com/matplotlib/basemap/blob/v{{ version }}/packages/basemap/doc/index.rst

  - name: basemap-data-hires
    version: 1.3.2
    script: build-basemap.sh  # [not win]
    script: bld-basemap.bat   # [win]
    build:
      noarch: python
    requirements:
      host:
        - pip
        - setuptools <60.0.0
      run:
        - python
        - {{ pin_subpackage('basemap-data') }}
    about:
      home: https://matplotlib.org/basemap
      license: LGPL-3.0-or-later
      license_family: LGPL
      license_file: packages/basemap_data_hires/COPYING.LESSER
      summary: High-resolution data assets for matplotlib basemap.
      dev_url: https://github.com/matplotlib/basemap
      doc_url: https://matplotlib.org/basemap/
      doc_source_url: https://github.com/matplotlib/basemap/blob/v{{ version }}/packages/basemap/doc/index.rst

about:
  home: https://matplotlib.org/basemap
  license: MIT
  license_family: MIT
  summary: Split for basemap.
  license_file:
    - packages/basemap/LICENSE

extra:
  recipe-maintainers:
    - molinav
    - ocefpaf
    - ReimarBauer
