appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ESHO3IQAsYAgHAS74dh4iC9L2kXKYQhj2K0i8O4axmrTdFf6vNrxf+Fnfb9U56k63qu+o5vBH66Kp2CR9T6eaH2Wg0KwOuKVSPiwmdc17QA/JGsgBldc4fiammT27pLRjgy+ewfNnxUMIlccMKXqVbTO6z+6pkzfJcr4gWlUjAN46eOWCcYZ2RiUdVCsUgZytEU7+EEO+optlp22h1ADNN8QBpVJ3MdK/G57P/VzBa+79ZTRfQUKzW9Vv4ub+T4AszRIprorx/ulL/XxgmN0qtEcSClBYdrMKl/3nZ5rK9jtqVkMLyCXhUV0oUoZMZ9M8VTRpM+ya99iHGEg2EazDmf4rI/H6TFKJtgRlVLz427EPnwq4JtNaozonsPizdHNu7JAY/rWf/h61aW3i3B/tqGW+RiuWKfsK7yBqgmPv/gHAzTSlD0yQEAXlirHEUJzrg/tbCB/5xxXKYjZZaFdDJZVHzeaULbW/MVVjOWdff1B7T+zyzbBj5xIymmqzYAaahFJDSLVxREwLH1hGJS2jMzwmlCFNZw8rRkv4hlC2OylyGWlogOQEgjqTRLJdE2pG+6sAQNKC3zswNNGGMUkOWUaVOrI4k/5nK6miJSQyUzXzGAhbZmX4f0YgOy3oI1KZ5f1Y0UxhMiC7GCRm6ROeDkEkYc4T1QQGUVxZ27U0SM=}
provider:
  osx: azure
  linux: azure
  win: azure

